import { describe, it, expect, beforeEach, afterEach } from "vitest";
import fs from "fs";
import path from "path";
import { tmpdir } from "os";
import { writeClaudeHooksDir, writeAgentWorkspace } from "../../src/orchestrator/orchestrator.js";
import type { AgentConfig } from "../../src/orchestrator/types.js";

const TMP_ROOT = path.join(tmpdir(), `bce-orch-write-${Date.now()}`);

beforeEach(() => {
  fs.mkdirSync(TMP_ROOT, { recursive: true });
});

afterEach(() => {
  try { fs.rmSync(TMP_ROOT, { recursive: true, force: true }); } catch {}
});

const FAKE_BCE_SCRIPT = [
  "#!/bin/bash",
  "# Generated by BCE — DO NOT EDIT",
  "# Lifecycle: session-start",
  "",
  "# From behavior: test-behavior (order: 5)",
  '"$BCE_SCRIPTS_DIR/test_script.sh" || true',
  "",
].join("\n");

const BCE_HOOKS = {
  "session-start": FAKE_BCE_SCRIPT,
  "post-tool-use": FAKE_BCE_SCRIPT.replace("session-start", "post-tool-use"),
  "session-stop": FAKE_BCE_SCRIPT.replace("session-start", "session-stop"),
};

const BCE_ENV_VARS = {
  COORDINATOR_AGENT_ID: "test-agent",
  COORDINATOR_AGENT_NAME: "Test Agent",
  COORDINATOR_AGENT_PROFILE: "codeur",
  COORDINATOR_AGENT_MODEL: "claude-opus-4-6",
};

describe("writeClaudeHooksDir", () => {
  it("writes settings.json with PascalCase nested hook format (regression lock for PR #5/#6)", () => {
    const claudeDir = path.join(TMP_ROOT, "pascal-case-lock", ".claude");
    writeClaudeHooksDir({ claudeDir, hooks: BCE_HOOKS, envVars: BCE_ENV_VARS });

    const settings = JSON.parse(fs.readFileSync(path.join(claudeDir, "settings.json"), "utf-8"));

    // Claude Code requires PascalCase event names — kebab-case is silently ignored
    expect(settings.hooks).toBeDefined();
    expect(settings.hooks.SessionStart).toBeDefined();
    expect(settings.hooks.PostToolUse).toBeDefined();
    expect(settings.hooks.Stop).toBeDefined();
    expect(settings.hooks["session-start"]).toBeUndefined();
    expect(settings.hooks["post-tool-use"]).toBeUndefined();
    expect(settings.hooks["session-stop"]).toBeUndefined();

    // Each event value is an array of entries with a nested `hooks[]` array
    expect(Array.isArray(settings.hooks.SessionStart)).toBe(true);
    expect(settings.hooks.SessionStart[0].hooks).toBeDefined();
    expect(settings.hooks.SessionStart[0].hooks[0].type).toBe("command");
    expect(settings.hooks.SessionStart[0].hooks[0].command).toContain("bash");

    // PostToolUse needs a matcher so it only fires on Edit|Write|NotebookEdit
    expect(settings.hooks.PostToolUse[0].matcher).toBe("Edit|Write|NotebookEdit");
  });

  it("writes .coordinator-env with shell-quoted export lines", () => {
    const claudeDir = path.join(TMP_ROOT, "env-export", ".claude");
    writeClaudeHooksDir({
      claudeDir,
      hooks: BCE_HOOKS,
      envVars: { ...BCE_ENV_VARS, WEIRD_KEY: "value with 'quotes'" },
    });

    const envContent = fs.readFileSync(path.join(claudeDir, ".coordinator-env"), "utf-8");

    expect(envContent).toContain("export COORDINATOR_AGENT_ID='test-agent'");
    expect(envContent).toContain("export COORDINATOR_AGENT_NAME='Test Agent'");
    // Single quote in value must be escaped via '\''
    expect(envContent).toContain("export WEIRD_KEY='value with '\\''quotes'\\'''");
  });

  it("resolves $BCE_SCRIPTS_DIR to an absolute path in the hook scripts", () => {
    const claudeDir = path.join(TMP_ROOT, "bce-resolve", ".claude");
    writeClaudeHooksDir({ claudeDir, hooks: BCE_HOOKS, envVars: BCE_ENV_VARS });

    const hookScript = fs.readFileSync(path.join(claudeDir, "hooks", "session-start.sh"), "utf-8");
    expect(hookScript).not.toContain("$BCE_SCRIPTS_DIR");
    expect(hookScript).toMatch(/[/\\]scripts[/\\]test_script\.sh/);
  });

  // POSIX seulement : Windows n'implémente pas les bits de permission POSIX.
  // fs.chmod n'y pilote que l'attribut lecture-seule, si bien qu'un fichier écrit
  // avec `{ mode: 0o755 }` ressort en 0o666 et que le bit d'exécution vaut 0 —
  // l'assertion ne peut jamais tenir. Ce n'est pas un défaut du produit : le mode
  // compte sur les plateformes où les hooks s'exécutent réellement, et il y est
  // toujours vérifié.
  it.skipIf(process.platform === "win32")("writes hook scripts with 0o755 permissions", () => {
    const claudeDir = path.join(TMP_ROOT, "perms", ".claude");
    writeClaudeHooksDir({ claudeDir, hooks: BCE_HOOKS, envVars: BCE_ENV_VARS });

    const stat = fs.statSync(path.join(claudeDir, "hooks", "session-start.sh"));
    // Check that owner has execute permission
    expect(stat.mode & 0o100).toBe(0o100);
  });

  it("returns writtenFiles[] with every file it created", () => {
    const claudeDir = path.join(TMP_ROOT, "written-files", ".claude");
    const result = writeClaudeHooksDir({ claudeDir, hooks: BCE_HOOKS, envVars: BCE_ENV_VARS });

    expect(result.writtenFiles).toHaveLength(5); // 3 hooks + env + settings
    expect(result.writtenFiles).toContain(result.settingsPath);
    expect(result.writtenFiles).toContain(result.envPath);
    expect(result.writtenFiles.some((f) => f.endsWith("session-start.sh"))).toBe(true);
    expect(result.writtenFiles.some((f) => f.endsWith("post-tool-use.sh"))).toBe(true);
    expect(result.writtenFiles.some((f) => f.endsWith("session-stop.sh"))).toBe(true);
  });

  it("hook command single-quotes both the inner paths and the outer bash -c arg", () => {
    const claudeDir = path.join(TMP_ROOT, "shell-escape", ".claude");
    writeClaudeHooksDir({ claudeDir, hooks: BCE_HOOKS, envVars: BCE_ENV_VARS });
    const settings = JSON.parse(fs.readFileSync(path.join(claudeDir, "settings.json"), "utf-8"));
    const cmd: string = settings.hooks.SessionStart[0].hooks[0].command;

    // The inner source/bash args are single-quoted (not double-quoted)
    // so $, ", `, \ in paths stay literal. We check that no unquoted
    // variable-expansion sequences leak through.
    expect(cmd).toContain("source '");
    expect(cmd).toContain("bash '");
    expect(cmd).not.toMatch(/source "/);
    expect(cmd).not.toMatch(/ bash "/);
  });

  it("preserves existingSettings fields other than hooks", () => {
    const claudeDir = path.join(TMP_ROOT, "preserve", ".claude");
    writeClaudeHooksDir({
      claudeDir,
      hooks: BCE_HOOKS,
      envVars: BCE_ENV_VARS,
      existingSettings: { editor: { tabSize: 4 }, hooks: { IgnoreMe: [] } },
    });
    const settings = JSON.parse(fs.readFileSync(path.join(claudeDir, "settings.json"), "utf-8"));
    expect(settings.editor).toEqual({ tabSize: 4 });
    expect(settings.hooks.IgnoreMe).toBeUndefined();
    expect(settings.hooks.SessionStart).toBeDefined();
  });

  // #172 — un `essaim init` par-dessus une settings.json qui a déjà des hooks
  // utilisateur ne doit PAS les effacer. On fusionne par événement (les hooks
  // essaim, repérés par la ligne `source .coordinator-env`, sont remplacés ;
  // le reste survit) et on sauvegarde l'ancien fichier en .bak.
  it("merges essaim hooks with a pre-existing user hook instead of clobbering, and backs up the old file (#172)", () => {
    const claudeDir = path.join(TMP_ROOT, "merge-user-hooks", ".claude");
    fs.mkdirSync(claudeDir, { recursive: true });
    const userSettings = {
      editor: { tabSize: 2 },
      hooks: {
        // événement qu'essaim n'écrit jamais → doit rester intact
        UserPromptSubmit: [{ hooks: [{ type: "command", command: "my-prompt-guard.sh" }] }],
        // événement partagé avec essaim → l'utilisateur ET essaim doivent coexister
        PostToolUse: [{ matcher: "Bash", hooks: [{ type: "command", command: "my-bash-audit.sh" }] }],
      },
    };
    const settingsPath = path.join(claudeDir, "settings.json");
    fs.writeFileSync(settingsPath, JSON.stringify(userSettings, null, 2));

    writeClaudeHooksDir({ claudeDir, hooks: BCE_HOOKS, envVars: BCE_ENV_VARS, existingSettings: userSettings });

    const settings = JSON.parse(fs.readFileSync(settingsPath, "utf-8"));
    const cmds = (event: string): string[] =>
      (settings.hooks[event] ?? []).flatMap((e: { hooks: { command: string }[] }) => e.hooks.map((h) => h.command));
    expect(settings.editor).toEqual({ tabSize: 2 });
    expect(cmds("UserPromptSubmit")).toContain("my-prompt-guard.sh");
    expect(cmds("PostToolUse").some((c) => c.includes("my-bash-audit.sh"))).toBe(true);
    expect(cmds("PostToolUse").some((c) => c.includes(".coordinator-env"))).toBe(true);
    expect(settings.hooks.SessionStart).toBeDefined();
    expect(fs.existsSync(settingsPath + ".bak")).toBe(true);
    expect(JSON.parse(fs.readFileSync(settingsPath + ".bak", "utf-8"))).toEqual(userSettings);
  });

  it("re-running init does not duplicate essaim's own hook entry (#172 idempotent)", () => {
    const claudeDir = path.join(TMP_ROOT, "idempotent-hooks", ".claude");
    writeClaudeHooksDir({ claudeDir, hooks: BCE_HOOKS, envVars: BCE_ENV_VARS });
    const settingsPath = path.join(claudeDir, "settings.json");
    const first = JSON.parse(fs.readFileSync(settingsPath, "utf-8"));
    writeClaudeHooksDir({ claudeDir, hooks: BCE_HOOKS, envVars: BCE_ENV_VARS, existingSettings: first });
    const second = JSON.parse(fs.readFileSync(settingsPath, "utf-8"));
    const essaimCount = (event: string): number =>
      (second.hooks[event] ?? []).filter((e: { hooks: { command: string }[] }) =>
        e.hooks.some((h) => typeof h.command === "string" && h.command.includes(".coordinator-env")),
      ).length;
    expect(essaimCount("SessionStart")).toBe(1);
    expect(essaimCount("PostToolUse")).toBe(1);
    expect(essaimCount("Stop")).toBe(1);
  });

  // #172 (revue adverse) — le marqueur ne doit PAS être un substring nu
  // `.coordinator-env` : un hook utilisateur qui source lui-même l'env, ou une
  // commande qui mentionne un chemin voisin, doit survivre.
  it("does not clobber a user hook that merely references .coordinator-env (#172 tight marker)", () => {
    const claudeDir = path.join(TMP_ROOT, "tight-marker", ".claude");
    fs.mkdirSync(claudeDir, { recursive: true });
    const userSettings = {
      hooks: {
        // source l'env essaim pour SON propre setup — n'est PAS une entrée essaim
        SessionStart: [{ hooks: [{ type: "command", command: "source .claude/.coordinator-env && my-extra-setup.sh" }] }],
        // sur-correspondance de substring : un chemin qui préfixe .coordinator-env
        PreToolUse: [{ matcher: "Bash", hooks: [{ type: "command", command: "guard --log .coordinator-env-audit.log" }] }],
      },
    };
    fs.writeFileSync(path.join(claudeDir, "settings.json"), JSON.stringify(userSettings, null, 2));

    writeClaudeHooksDir({ claudeDir, hooks: BCE_HOOKS, envVars: BCE_ENV_VARS, existingSettings: userSettings });

    const settings = JSON.parse(fs.readFileSync(path.join(claudeDir, "settings.json"), "utf-8"));
    const cmds = (event: string): string[] =>
      (settings.hooks[event] ?? []).flatMap((e: { hooks: { command: string }[] }) => e.hooks.map((h) => h.command));
    expect(cmds("SessionStart").some((c) => c.includes("my-extra-setup.sh"))).toBe(true);
    expect(cmds("PreToolUse")).toContain("guard --log .coordinator-env-audit.log");
    // l'entrée essaim (vraie forme source+bash+/hooks/) s'ajoute quand même à côté
    expect(cmds("SessionStart").some((c) => c.includes("hooks"))).toBe(true);
  });
});

function makeAgent(partial: Partial<AgentConfig> & Pick<AgentConfig, "id" | "name" | "profile">): AgentConfig {
  return {
    prompt: "",
    hooks: BCE_HOOKS,
    envVars: BCE_ENV_VARS,
    mcpTools: ["announce_work", "post_to_thread"],
    ...partial,
  };
}

describe("writeAgentWorkspace", () => {
  it("writes .mcp.json pointing at the coordinator URL", () => {
    const wsPath = path.join(TMP_ROOT, "mcp-config");
    fs.mkdirSync(wsPath, { recursive: true });
    const agent = makeAgent({ id: "agent-1", name: "Agent One", profile: "codeur" });

    const mcpPath = writeAgentWorkspace(wsPath, agent, "http://localhost:9999");

    expect(mcpPath).toBe(path.join(wsPath, ".mcp.json"));
    const mcpConfig = JSON.parse(fs.readFileSync(mcpPath, "utf-8"));
    expect(mcpConfig.mcpServers.coordinator.type).toBe("http");
    expect(mcpConfig.mcpServers.coordinator.url).toBe("http://localhost:9999/mcp");
  });

  it("writes .claude/ via writeClaudeHooksDir with COORDINATOR_URL merged in", () => {
    const wsPath = path.join(TMP_ROOT, "claude-dir");
    fs.mkdirSync(wsPath, { recursive: true });
    const agent = makeAgent({ id: "agent-2", name: "Agent Two", profile: "codeur" });

    writeAgentWorkspace(wsPath, agent, "http://coord.test");

    // Hooks were written in PascalCase format
    const settings = JSON.parse(fs.readFileSync(path.join(wsPath, ".claude", "settings.json"), "utf-8"));
    expect(settings.hooks.SessionStart).toBeDefined();
    expect(settings.hooks.PostToolUse[0].matcher).toBe("Edit|Write|NotebookEdit");

    // COORDINATOR_URL is injected on top of BCE envVars
    const envContent = fs.readFileSync(path.join(wsPath, ".claude", ".coordinator-env"), "utf-8");
    expect(envContent).toContain("export COORDINATOR_URL='http://coord.test'");
    // BCE envVars from the agent config are preserved
    expect(envContent).toContain("export COORDINATOR_AGENT_ID='test-agent'");
  });

  it("works for communicant profile too (no profile-specific branching)", () => {
    const wsPath = path.join(TMP_ROOT, "communicant");
    fs.mkdirSync(wsPath, { recursive: true });
    const agent = makeAgent({ id: "comm-1", name: "Communicant One", profile: "communicant" });

    writeAgentWorkspace(wsPath, agent, "http://localhost:3100");

    expect(fs.existsSync(path.join(wsPath, ".mcp.json"))).toBe(true);
    expect(fs.existsSync(path.join(wsPath, ".claude", "settings.json"))).toBe(true);
    expect(fs.existsSync(path.join(wsPath, ".claude", "hooks", "session-start.sh"))).toBe(true);
  });
});

